### ISSUE TITLE
Plotly graphs not rendering 

### ISSUE THREAD

**Issue by StefanTodoran** [geo-smart/mlgeo-book#1]
Plotly graphs do not show up on the github pages site. Here is how a rendered graph from 2.3_pandas_rendered.ipynb looks in visual studio code:

![image](https://user-images.githubusercontent.com/16695001/200055537-510e43a6-7a45-4b3e-90e9-b4bfb9c2854c.png)

And here is how it looks on the website. Note that if you use inspect element to inspect the section in question, you will notice that the "cell_output docutils container" that should have the graph is completely empty.

![image](https://user-images.githubusercontent.com/16695001/200056449-284e82e7-b3f7-458e-8682-1104bbdc9f18.png)
There are a number of possible reasons, the following are ones that I have tried and have not remedied the problem:

- According to https://jupyterbook.org/en/stable/interactive/interactive.html,  Including plotly plots in a Jupyter Book page is [currently not compatible](https://github.com/executablebooks/jupyter-book/issues/1528) with the dollarmath syntax extension (mathematical notation written between two “$” characters). However the current version of 2.3_pandas_rendered.ipynb does not include any dollarmath and the graph still does not render.
- It is necessary to load require.js in _config.yml, this has been done and is not the issue.
- It is configured it _config.yml for notebooks with "rendered" in the name to not be re-executed, (see exclude_patterns: ["*rendered*", "*skip*"] in _config.yml) however this did not fix the issue either.
- There may be other fixes I tried but these are all that I remember.

I have not yet reproduced this is another jupyter notebook, that is the next step at the moment.

**Comment by StefanTodoran** [comment]
Update:
So I tried downloading the .ipynb from [here](https://jupyterbook.org/en/stable/interactive/interactive.html) and putting it in the geosmart use case book and was able to reproduce the same effect. Therefore it seems likely that the issue exists in the GeoSMART hackweek jupyter book template from which both this book and the use case book where made.

**Comment by StefanTodoran** [comment]
I have located the issue. The environment in which the build workflow runs in during the github action doesn't have pandas, so execution of the notebook in question fails. 

This is odd, since the `environment.yml` file does include pandas. This means the setupconda action is failing. This likely has something to do with the fact that it uses the lock files, which are a relic from the hackweek template and are unused/updated.

Either the setupconda action needs to be change so as to build directly from `environment.yml` or the lock files need to be updated somehow.

**Comment by mdenolle** [comment]
No longer needed -  we are choosing a minimalist approach with limited dependencies.
